### ISSUE TITLE
Usability improvements to post-processing config

### ISSUE THREAD

**Issue by pineapple-cat** [ukri-excalibur/excalibur-tests#255]
So far, the post-processing config has been relatively limited to practical settings that are required for graph functionality. Now that a wider range of useful categorical plots can be produced with the help of more flexible sorting, filtering, and scaling features, the introduction of more cosmetic or quality of life settings would not go amiss. Some previously suggested features include:

- [ ] user-specified x-axis label orientation (e.g. `horizontal` by default, with the option of `vertical` to prevent long labels from overlapping, see #213)
- [ ] a toggle to automatically save a plot to PNG (and also perhaps a toggle to forgo automatically saving a plot to HTML)
- [x] a toggle to dump a csv file of selected dataframe (or at some other stage after sorting) - being worked on in #260 
- [ ] a toggle to drop rows with missing/NaN values (see #253)
- [ ] more convenient ways to select series values, particularly the ability to select all values in a series column (e.g. `series: [["series_col",*]]`) ( see #235)
- [ ] change optional list fields to no longer be required in the config (e.g. `config["series"]` --> `config.get("series")` and respond appropriately if `None`)

**Comment by kaanolgu** [comment]
I could work on csv export of the dataframe since it is also going to be used for the Babelstream if it is OK ?
